# Generated by Django 5.0.7 on 2024-07-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2007', '0002_muallif_tugigan_yil'),
    ]

    operations = [
        migrations.AddField(
            model_name='muallif',
            name='jinsi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
