# Generated by Django 5.0.7 on 2024-07-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2007', '0003_muallif_jinsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='muallif',
            name='kitob_soni',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
