# Generated by Django 5.0.7 on 2024-07-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2007', '0004_muallif_kitob_soni'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='turi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='oquvchi',
            name='kitob_soni',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
