# Generated by Django 5.0.7 on 2024-08-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0808', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.DateField()),
                ('malumot', models.CharField(max_length=50)),
                ('faol', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tododescription',
        ),
        migrations.DeleteModel(
            name='Todostatus',
        ),
        migrations.DeleteModel(
            name='Todotime',
        ),
    ]
